=== JosueVillanueva/WTTH/etc/config/inventoryTree/inventoryTree.dtd
<!--
  ==========================================================================
  Inventory Tree definition DTD in
  HPE Service Activator version 8.0.

  ==========================================================================
  (c) Copyright 2008-2016 Hewlett Packard Enterprise Development LP
  ==========================================================================
-->

<!-- Used in several places -->
<!ELEMENT Value (#PCDATA)>	
<!ATTLIST Value
    bold (true|false) #IMPLIED
    italic (true|false) #IMPLIED
    textColor CDATA #IMPLIED
    bundle CDATA #IMPLIED
>   

<!-- The root for inventory definitions -->
<!ELEMENT InventoryTree (Name, SequenceNumber?, Solution?, Description?, DataSource?, OperationTypeName*, BranchTypeName*, Branch*, Filter?, InitialCasePacket?)>

<!-- default will be used to indicate if this tree will be open automatically in inventory UI. Default value will be "false" if not set. -->
<!-- allowClassView will be used to indicate if class view tree will be enabled. -->
<!ATTLIST InventoryTree
	default (true|false) #IMPLIED
    allowClassView (true|false) #IMPLIED
    bundle CDATA #IMPLIED
>

<!ELEMENT Name (#PCDATA)>
<!-- bundle will be used to use a specific bundle -->
<!ATTLIST Name
    bundle CDATA #IMPLIED
>

<!ELEMENT SequenceNumber (#PCDATA)>
<!ELEMENT Solution (Name, Label?)>
<!ELEMENT Description (#PCDATA)>
<!ELEMENT DataSource (#PCDATA)>
<!ELEMENT OperationTypeName (Name, Description?)>
<!ELEMENT BranchTypeName (Name, Description?)>

<!ELEMENT Branch (Name, DefName?, Condition*, BranchType?, Type?, Image*, ReservedImage?, Class-Name?, Find-By*, Font*, Label*, Scroll?, Parent-Find-By? ,Children?, Operation*, DefOperation*)>

<!-- definedSearch will be used to modify default action to implement searches -->
<!ATTLIST Branch
    definedSearch CDATA #IMPLIED
    advancedSearch CDATA #IMPLIED
    bundle CDATA #IMPLIED
    expand CDATA #IMPLIED
>

<!ELEMENT BranchType (#PCDATA)>
<!ELEMENT DefName (#PCDATA)>
<!-- bundle will be used to use a specific bundle -->
<!ATTLIST DefName
    bundle CDATA #IMPLIED
>

<!-- role will be used to check if current login user belongs to this role. role can be set to a constant or a variable. -->
<!ELEMENT Condition (#PCDATA)>
<!ATTLIST Condition
	role CDATA #IMPLIED
>

<!ELEMENT Type (#PCDATA)>
<!ELEMENT Image (#PCDATA | Condition | Value)*>
<!ELEMENT ReservedImage (#PCDATA)>
<!ELEMENT Class-Name (#PCDATA)>
<!ELEMENT Font (#PCDATA | Condition | TextColor)*>
<!-- bold: default value is false -->
<!-- italic: default value is false -->
<!ATTLIST Font
	bold (true|false) #IMPLIED
	italic (true|false) #IMPLIED
>	
<!ELEMENT TextColor (#PCDATA)>

<!ELEMENT Label (#PCDATA | Condition | Value)*>
<!ATTLIST Label
    bundle CDATA #IMPLIED
>
<!ELEMENT Scroll (#PCDATA)>

<!ELEMENT Children (Child*)>
	<!ELEMENT Child (#PCDATA)>

<!-- Operation: the operations that will be available in instance view -->
<!ELEMENT Operation (Name, Condition*, Image+, Object?, OperationType?, Action)>

<!-- flag attribute: 
	"reserve" stands for reserve resource operation. 
	"release" stands for release resource operation.
-->
<!ATTLIST Operation
	default (true|false) #IMPLIED
	warning (true|false) #IMPLIED
	flag (reserve|release) #IMPLIED
	bundle CDATA #IMPLIED 
>

<!-- DefOperation: the operations that will be available in class view -->
<!ELEMENT DefOperation (Name, Image, Object?, OperationType?, Action)>

<!-- defFlag attribute:
	"extend" stands for extend attribute operation. 
-->
<!ATTLIST DefOperation
	default (true|false) #IMPLIED
	warning (true|false) #IMPLIED	
	defFlag (extend) #IMPLIED
    bundle CDATA #IMPLIED 
>

<!ELEMENT Object (#PCDATA)>
<!ELEMENT OperationType (#PCDATA)>
<!ELEMENT Action (Page, Param*,Workflow?)>
<!ELEMENT Page (#PCDATA)>
<!ELEMENT Param (Name, Value)>
<!ELEMENT Workflow (Name,Label?,Bean*, WFParam*, Result*)>
<!ATTLIST Workflow
	 method  (startJob|startAndWaitForJob) #IMPLIED
>
<!ELEMENT Bean (Name, Class-Name, Find-By)>
<!ELEMENT WFParam (Name, DisplayName?, Description?,BeanName?, PValue*)> 
<!ATTLIST WFParam 	
    source (branch|bean) #IMPLIED
    dataType (String|int|float|long|double|boolean|Date)  #IMPLIED
    dateFormat CDATA #IMPLIED
    editable (true|false)	 #IMPLIED
    dropdown (true|false)	#IMPLIED
>
<!ELEMENT PValue (#PCDATA)>
<!ATTLIST PValue
	default (true|false)  #IMPLIED
>
<!ELEMENT DisplayName (#PCDATA)>
<!ELEMENT BeanName (#PCDATA)>
<!ELEMENT Result (Name, DisplayName?) >



<!ELEMENT Find-By (Condition*, Method, Key*)>
<!ELEMENT Parent-Find-By (Method, Key*)>
<!ELEMENT Method (#PCDATA)>
<!ELEMENT Key (#PCDATA)>
<!-- parentKey: default value is false-->
<!-- type: default value is String-->
<!ATTLIST Key
	parentKey (true|false) #IMPLIED
	type (int|long|float|double|boolean|Date|String) #IMPLIED
>
	
<!ELEMENT InitialCasePacket (VariableValue*)>
<!ELEMENT VariableValue (#PCDATA)>
<!ATTLIST VariableValue
	name CDATA #REQUIRED
	value CDATA #REQUIRED
>

    
<!-- Filter -->
<!ELEMENT Filter (Field*)>
<!ATTLIST Filter
	expand CDATA #IMPLIED
>
<!ELEMENT Field (ListOfValues?)>
<!ATTLIST Field
    variable CDATA #REQUIRED
    label CDATA #IMPLIED
    bundle CDATA #IMPLIED
    type (text|checkbox|select|date) #REQUIRED
    group CDATA #IMPLIED
>
<!ELEMENT ListOfValues (Value+ | (BeanName, Attribute?, Method?, ParameterValue*))>
<!ELEMENT Attribute (#PCDATA)>
<!ELEMENT ParameterValue (#PCDATA)>

=== JosueVillanueva/WTTH/etc/config/inventoryTree/Claro_WTTH_Tree.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE InventoryTree SYSTEM "inventoryTree.dtd">

<InventoryTree>
   <Name>WTTH</Name>
   <Solution>
      <Name>WTTH</Name>
      <Label>
         <Value bold="false" italic="false">HPESA</Value>
      </Label>
   </Solution>
   <Description>Arbol Tablas General</Description>
   <OperationTypeName>
      <Name>Create</Name>
   </OperationTypeName>
   <OperationTypeName>
      <Name>View</Name>
   </OperationTypeName>
   <OperationTypeName>
      <Name>Edit</Name>
   </OperationTypeName>
   <OperationTypeName>
      <Name>Delete</Name>
   </OperationTypeName>
   <BranchTypeName>
      <Name>General</Name>
   </BranchTypeName>
   <Branch>
      <Name>WTTH</Name>
      <DefName>WTTH</DefName>
      <Image>customer.gif</Image>
      <Label>
         <Value bold="false" italic="false">WTTH</Value>
      </Label>
      <Children>
         <Child>Customer</Child>
         <Child>Services</Child>
         <Child>Service_Params</Child>
         <Child>Service_Mapping</Child>
         <Child>Action_Templates</Child>
         <Child>Network_Element</Child>
         <Child>Error_Handling</Child>
         <Child>Configuration_Params</Child>
         <Child>lrt_ims_to_mov</Child>
         <Child>lrt_mov_to_ims</Child>
      </Children>
   </Branch>
   <Branch>
      <Name>Customer</Name>
      <DefName>Customer</DefName>
      <BranchType>General</BranchType>
      <Type>General</Type>
      <Image>customer.gif</Image>
      <Label>
         <Value bold="false" italic="false">constant:Customer</Value>
      </Label>
      <Children>
         <Child>GENSERV_CUSTOMER</Child>
      </Children>
      <Operation>
         <Name>Create Customer</Name>
         <Image>customer.gif</Image>
         <OperationType>Create</OperationType>
         <Action>
            <Page>CreationFormCustomerAction.do</Page>
         </Action>
      </Operation>
   </Branch>
   <Branch>
      <Name>GENSERV_CUSTOMER</Name>
      <DefName>GENSERV_CUSTOMER</DefName>
      <Image>software.gif</Image>
      <Class-Name>com.hpe.ov.activator.inventory.Customer</Class-Name>
      <Find-By>
         <Method>findAll</Method>
      </Find-By>
      <Label>
         <Value bold="false" italic="false">$GENSERV_CUSTOMER.CUSTOMER_ID$ - $GENSERV_CUSTOMER.CUSTOMER$</Value>
      </Label>
      <Operation default="true">
         <Name>View</Name>
         <Image>customer.gif</Image>
         <Object>GENSERV_CUSTOMER</Object>
         <OperationType>View</OperationType>
         <Action>
            <Page>ViewFormCustomerAction.do</Page>
            <Param>
               <Name>CUSTOMER</Name>
               <Value>GENSERV_CUSTOMER.CUSTOMER_ID</Value>
            </Param>
         </Action>
      </Operation>
      <Operation>
         <Name>Edit</Name>
         <Image>edit.gif</Image>
         <Object>CUSTOMER</Object>
         <OperationType>Edit</OperationType>
         <Action>
            <Page>UpdateFormCustomerAction.do</Page>
            <Param>
               <Name>CUSTOMER</Name>
               <Value>GENSERV_CUSTOMER.CUSTOMER_ID</Value>
            </Param>
         </Action>
      </Operation>
      <Operation>
         <Name>Delete</Name>
         <Image>delete.gif</Image>
         <Object>CUSTOMER</Object>
         <OperationType>Delete</OperationType>
         <Action>
            <Page>DeleteFormCustomerAction.do</Page>
            <Param>
               <Name>COSTUMER</Name>
               <Value>GENSERV_COSTUMER.COSTUMER_ID</Value>
            </Param>
         </Action>
      </Operation>
      <Operation>
         <Name>Create</Name>
         <Image>services.gif</Image>
         <OperationType>Create</OperationType>
         <Action>
            <Page>CreationFormCustomerAction.do</Page>
         </Action>
      </Operation>
   </Branch>
   <Branch>
      <Name>Services</Name>
      <DefName>Services</DefName>
      <BranchType>General</BranchType>
      <Type>General</Type>
      <Image>services.gif</Image>
      <Label>
         <Value bold="false" italic="false">constant:Services</Value>
      </Label>
      <Children>
         <Child>GENSERV_SERVICES</Child>
      </Children>
      <Operation>
         <Name>Create Services</Name>
         <Image>package.gif</Image>
         <OperationType>Create</OperationType>
         <Action>
            <Page>CreationFormServicesAction.do</Page>
         </Action>
      </Operation>
   </Branch>
   <Branch>
      <Name>GENSERV_SERVICES</Name>
      <DefName>GENSERV_SERVICES</DefName>
      <Image>software.gif</Image>
      <Class-Name>com.hpe.ov.activator.inventory.Services</Class-Name>
      <Find-By>
         <Method>findAll</Method>
      </Find-By>
      <Label>
         <Value bold="false" italic="false">$GENSERV_SERVICES.SERVICE_ID$</Value>
      </Label>
      <Operation default="true">
         <Name>View</Name>
         <Image>services.gif</Image>
         <Object>SERVICES</Object>
         <OperationType>View</OperationType>
         <Action>
            <Page>ViewFormServicesAction.do</Page>
            <Param>
               <Name>SERVICE_ID</Name>
               <Value>GENSERV_SERVICES.SERVICE_ID</Value>
            </Param>
         </Action>
      </Operation>
      <Operation>
         <Name>Edit</Name>
         <Image>edit.gif</Image>
         <Object>SERVICES</Object>
         <OperationType>Edit</OperationType>
         <Action>
            <Page>UpdateFormServicesAction.do</Page>
            <Param>
               <Name>SERVICE_ID</Name>
               <Value>GENSERV_SERVICES.SERVICE_ID</Value>
            </Param>
         </Action>
      </Operation>
      <Operation>
         <Name>Delete</Name>
         <Image>delete.gif</Image>
         <Object>SERVICES</Object>
         <OperationType>Delete</OperationType>
         <Action>
            <Page>DeleteFormServicesAction.do</Page>
            <Param>
               <Name>SERVICE_ID</Name>
               <Value>GENSERV_SERVICES.SERVICE_ID</Value>
            </Param>
         </Action>
      </Operation>
      <Operation>
         <Name>Create Service</Name>
         <Image>services.gif</Image>
         <OperationType>Create</OperationType>
         <Action>
            <Page>CreationFormServicesAction.do</Page>
         </Action>
      </Operation>
   </Branch>
   <Branch>
      <Name>Service_Params</Name>
      <DefName>Service_Params</DefName>
      <BranchType>General</BranchType>
      <Type>General</Type>
      <Image>services.gif</Image>
      <Label>
         <Value bold="false" italic="false">constant:Service_Params</Value>
      </Label>
      <Children>
         <Child>GENSERV_SERVICE_PARAMS</Child>
      </Children>
      <Operation>
         <Name>Create</Name>
         <Image>services.gif</Image>
         <OperationType>Create</OperationType>
         <Action>
            <Page>CreationFormServiceParamsAction.do</Page>
         </Action>
      </Operation>
   </Branch>
   <Branch>
      <Name>GENSERV_SERVICE_PARAMS</Name>
      <DefName>GENSERV_SERVICE_PARAMS</DefName>
      <Image>software.gif</Image>
      <Class-Name>com.hpe.ov.activator.inventory.ServiceParams</Class-Name>
      <Find-By>
         <Method>findAll</Method>
      </Find-By>
      <Label>
         <Value bold="false" italic="false">$GENSERV_SERVICE_PARAMS.PARAM_NAME$</Value>
      </Label>
      <Operation default="true">
         <Name>View</Name>
         <Image>services.gif</Image>
         <Object>GENSERV_SERVICE_PARAMS</Object>
         <OperationType>View</OperationType>
         <Action>
            <Page>ViewFormServiceParamsAction.do</Page>
            <Param>
               <Name>PARAM_NAME</Name>
               <Value>GENSERV_SERVICE_PARAMS.PARAM_NAME</Value>
            </Param>
         </Action>
      </Operation>
      <Operation>
         <Name>Edit</Name>
         <Image>edit.gif</Image>
         <Object>GENSERV_SERVICE_PARAMS</Object>
         <OperationType>Edit</OperationType>
         <Action>
            <Page>UpdateFormServiceParamsAction.do</Page>
            <Param>
               <Name>PARAM_NAME</Name>
               <Value>GENSERV_SERVICE_PARAMS.PARAM_NAME</Value>
            </Param>
         </Action>
      </Operation>
      <Operation>
         <Name>Delete</Name>
         <Image>delete.gif</Image>
         <Object>GENSERV_SERVICE_PARAMS</Object>
         <OperationType>Delete</OperationType>
         <Action>
            <Page>DeleteFormServiceParamsAction.do</Page>
            <Param>
               <Name>PARAM_NAME</Name>
               <Value>GENSERV_SERVICE_PARAMS.PARAM_NAME</Value>
            </Param>
         </Action>
      </Operation>
      <Operation>
         <Name>Create</Name>
         <Image>services.gif</Image>
         <OperationType>Create</OperationType>
         <Action>
            <Page>CreationFormServiceParamsAction.do</Page>
         </Action>
      </Operation>
   </Branch>
   <Branch>
      <Name>Service_Mapping</Name>
      <DefName>Service_Mapping</DefName>
      <BranchType>General</BranchType>
      <Type>General</Type>
      <Image>services.gif</Image>
      <Label>
         <Value bold="false" italic="false">constant:Service_Mapping</Value>
      </Label>
      <Children>
         <Child>GENSERV_SERVICE_MAPPING</Child>
      </Children>
      <Operation>
         <Name>Create</Name>
         <Image>services.gif</Image>
         <OperationType>Create</OperationType>
         <Action>
            <Page>CreationFormServiceMappingAction.do</Page>
         </Action>
      </Operation>
   </Branch>
   <Branch>
      <Name>GENSERV_SERVICE_MAPPING</Name>
      <DefName>GENSERV_SERVICE_MAPPING</DefName>
      <Image>software.gif</Image>
