=== JosueVillanueva/WTTH/deploy.dtd
<!--
  =============================================================================
    DTD for the HPE Service Activator solution deployment configuration file
  =============================================================================
-->

<!-- (c) Copyright 2008-2016 Hewlett Packard Enterprise Development LP -->

<!-- Top-level XML elements -->
<!ELEMENT Solution (Name, Backup?, Plugins?, CT?, Third-Party-Lib?, UI?, Inventory?, Inventory-Trees?, UMM?, Queue?, Workflows?, 
          Web-Services?, XMaps?, Config?, Templates?, Designer?, NLS?, Messages?, SQL?, Scripts?, Other?)>

<!-- Solution name -->
<!ELEMENT Name            (#PCDATA)>

<!-- Backup directory name -->
<!ELEMENT Backup          (#PCDATA)>

<!-- List of plug-ins -->
<!ELEMENT Plugins (File*, Core-File*)>
<!ELEMENT Core-File (#PCDATA)>
<!ATTLIST Core-File delete (true|false) #IMPLIED>

<!-- List of compound tasks -->
<!ELEMENT CT (File+)>

<!-- Java classes, archieves, properties, etc. -->
<!ELEMENT Third-Party-Lib (File+)>

<!-- Custom UI components (JSPs, Java servlets, JavaScripts, etc.) -->
<!ELEMENT UI (File+)>

<!-- Inventory components -->
<!ELEMENT Inventory      (Resources | Output+)>
<!ATTLIST Inventory db CDATA #IMPLIED>

<!ELEMENT Resources      (File+)>
<!ATTLIST Resources xmlpath CDATA #IMPLIED>
<!ATTLIST Resources classpath CDATA #IMPLIED>
<!ATTLIST Resources userClasspath CDATA #IMPLIED>
<!ATTLIST Resources userJsqlPath CDATA #IMPLIED>
<!ATTLIST Resources deployJSP CDATA #IMPLIED>
<!ATTLIST Resources overwrite CDATA #IMPLIED>
<!ATTLIST Resources convertPaths (true|false) #IMPLIED>
<!ATTLIST Resources outputDir CDATA #IMPLIED>
<!ELEMENT Output         (JAR?, JSP?, SQL?, Struts-Config?, Struts-Classes?)>
<!ELEMENT JAR            (File+)>
<!ELEMENT JSP            (File+)>
<!ELEMENT Struts-Config  (File+)>
<!ELEMENT Struts-Classes (File+)>
<!-- Solution version dependency for the Solution/Inventory/Output element -->
<!ATTLIST Output depend CDATA #IMPLIED>

<!-- Inventory Trees -->
<!ELEMENT Inventory-Trees (Tree-File+)>
<!ELEMENT Tree-File            (#PCDATA)>
<!ATTLIST Tree-File overwrite CDATA #IMPLIED>
<!ATTLIST Tree-File undeployForce CDATA #IMPLIED>
<!ATTLIST Tree-File delete (true|false) #IMPLIED>

<!-- UMM -->
<!ELEMENT UMM (File+)>

<!-- Queue -->
<!ELEMENT Queue (File+)>

<!-- List of workflows -->
<!ELEMENT Workflows (File+)>

<!-- Web Services -->
<!ELEMENT Web-Services (WSD*, war*)>
<!ELEMENT WSD          (jar*)>
<!ATTLIST WSD file CDATA #IMPLIED>
<!ATTLIST WSD overwrite CDATA #IMPLIED>
<!ELEMENT jar           (#PCDATA)>
<!ELEMENT war           (#PCDATA)>
<!ATTLIST war overwrite CDATA #IMPLIED>

<!-- List of xMaps  -->
<!ELEMENT XMaps (File+)>

<!-- List of Config (typically used for message syntax validation) -->
<!ELEMENT Config (File+)>

<!-- List of template files (Java templates, XML/XSL templates, etc.) -->
<!ELEMENT Templates (File+)>

<!-- List of custom Workflow Designer components (nodes and handlers) -->
<!ELEMENT Designer (File+)>

<!-- List of localized resource bundle files -->
<!ELEMENT NLS (File+)>

<!-- List of messages (typically used for testing purposes) -->
<!ELEMENT Messages (File+)>

<!-- SQL files to be executed during the deploy/undeploy process -->
<!ELEMENT SQL (Deploy*, Undeploy*)>
<!ELEMENT Deploy          (#PCDATA)>
<!ATTLIST Deploy db CDATA #IMPLIED>
<!ATTLIST Deploy fromMajor CDATA #IMPLIED>
<!ATTLIST Deploy fromMinor CDATA #IMPLIED>
<!ATTLIST Deploy fromRevision CDATA #IMPLIED>
<!ATTLIST Deploy toMajor CDATA #IMPLIED>
<!ATTLIST Deploy toMinor CDATA #IMPLIED>
<!ATTLIST Deploy toRevision CDATA #IMPLIED>
<!ATTLIST Deploy numeric CDATA #IMPLIED>

<!ELEMENT Undeploy        (#PCDATA)>
<!ATTLIST Undeploy db CDATA #IMPLIED>
<!-- Solution version dependency for the Solution/SQL/Deploy element -->
<!ATTLIST Deploy depend CDATA #IMPLIED>
<!-- Solution version dependency for the Solution/SQL/Undeploy element -->
<!ATTLIST Undeploy depend CDATA #IMPLIED>

<!-- Custom scripts to be executed before and after the deploy and undeploy operation -->
<!ELEMENT Scripts (Before-Deploy?, After-Deploy?, Before-Undeploy?, After-Undeploy?)>
<!ELEMENT Before-Deploy     (Script-Name, Argument*)>
<!ELEMENT After-Deploy      (Script-Name, Argument*)>
<!ELEMENT Before-Undeploy   (Script-Name, Argument*)>
<!ELEMENT After-Undeploy    (Script-Name, Argument*)>
<!ELEMENT Script-Name   (#PCDATA)>
<!ELEMENT Argument      (#PCDATA)>
<!-- Solution version dependency for the elements:
         Solution/Scripts/Before-Deploy/Script-Name
         Solution/Scripts/After-Deploy/Script-Name
         Solution/Scripts/Before-Undeploy/Script-Name
         Solution/Scripts/After-Undeploy/Script-Name
-->
<!ATTLIST Script-Name depend CDATA #IMPLIED>

<!-- Files to copied to and from custom locations -->
<!ELEMENT Other (Copy+)>
<!ELEMENT Copy            (#PCDATA)>
<!ATTLIST Copy src CDATA #REQUIRED>
<!ATTLIST Copy dest CDATA #REQUIRED>
<!ATTLIST Copy overwrite CDATA #IMPLIED>
<!ATTLIST Copy directory (true|false) #IMPLIED>
<!ATTLIST Copy executable (true|false) #IMPLIED>
<!ATTLIST Copy delete (true|false) #IMPLIED>

<!-- Miscellaneous -->
<!ELEMENT File            (#PCDATA)>
<!ATTLIST File overwrite CDATA #IMPLIED>
<!ATTLIST File solution (true|false) #IMPLIED>
<!ATTLIST File delete (true|false) #IMPLIED>
<!ATTLIST File executable (true|false) #IMPLIED>

=== JosueVillanueva/WTTH/deploy_WTTH.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Solution SYSTEM "deploy.dtd" >

<!--
  =============================================================================
    Sample configuration file for HPE Service Activator Solution deployment
  =============================================================================
-->

<!-- (c) Copyright 2008-2016 Hewlett Packard Enterprise Development LP -->

<!-- 
  INTRODUCTION
  =============================================================================
    This sample file demonstrates how write a "deploy.xml" file that is used
    to specify how a solution, a patch, or a customization is to be deployed
    in the HPE Service Activator runtime system.
    
    The <File> element is used in several places throughout this file.  For
    convenience the <File> element allows the use of simple wild-cards (*) as
    well as recursive wild-cards (**).  For example, the **/*.class pattern
    matches all files with the "class" extension in all sub-directories.

    In all cases the "deploy" operation will fail if a file in the runtime
    system is subject to be overwritten, unless the <File> element's
    'overwrite' attribute is set to 'true'.
    
    The <File> element also has an optional attribute called 'solution' with
    the default value 'false'.  The 'solution' attribute is only applicable
    for patches and customizations.  If the 'solution' attribute is set to
    'true' the Deployment Manager will copy the file from the patch or
    customization directory to the solution directory and NOT to the HP
    Service Activator runtime system when the patch or customization is'
    deployed.  If set to 'false', the file will be copied to the solution
    directory AND to the HPE Service Activator runtime system.
    
    The <File> element can be used to delete files by setting the value of the
    optional attribute 'delete' to 'true'.  The 'delete' attribute is only
    supported for patches and customizations.  (I.e. solutions can not use the
    'delete' attribute.)
    
    Finally, the <File> element has an optional attribute called 'executable'
    with the default value 'false'.  Setting this attribute to 'true' will
    cause the Deployment Manager to set the 'execute' bit after the file has
    been copied to the desired location.  The 'executable' attribute will not
    have an effect on Microsoft Windows systems.    
    
  THE SOLUTION DIRECTORY
  =============================================================================
    In order to use HPE Service Activator's built-in mechanisms for managing
    solution separation, all solutions must be located in the directory
    $ACTIVATOR_OPT/solutions/<SolutionName>.  The HPE Service Activator solution
    directory is structured as follows:
    
      <SolutionName>/
                    |-3rd-party/
                    |          |-classes/
                    |          |-lib/
                    |-bin/
                    |-CT/
                    |-docs/
                    |-etc/
                    |    |-config/
                    |    |       |-inventoryTree
                    |    |-data/
                    |    |-dc_tasks/
                    |    |-designer/
                    |    |         |-handlers/
                    |    |         |-nodes/
                    |    |-nls/
                    |    |-scripts/
                    |    |-queue/
                    |    |-sql/
                    |    |-template_files/
                    |    |-tests/
                    |    |      |-messages/
                    |    |-umm/
                    |    |-web_services/
                    |    |-workflows/
                    |    |-xmaps/
                    |-install/
                    |-inventory/
                    |-lib/
                    |-plugins/
                    |-UI/
                    |-var/
                    |    |-dc/
                    |    |-log/
                    |    |-tmp/
    
    The recommended use of the directories is described in the following:
      
      <SolutionName>/3rd-party/
        This directory is typically used for Java classes and Java archives
        implementing custom workflow nodes and modules.  There are, however,
        no restrictions to the usage of this directory.
        
      <SolutionName>/bin/
        This directory can be used as a place holder for executable files 
        (binary files as well as shell scripts) that are used as part of the
        solution.  The files in this directory will *not* be deployed into the
        HPE Service Activator runtime system.
        
      <SolutionName>/CT/
        This directory is used for solution specific compound tasks.
      
      <SolutionName>/docs/
        This directory can be used for containing documentation for the
        solution.  Files in this directory will *not* be deployed into the HP
        Service Activator runtime system.
        
      <SolutionName>/etc/config/
        This directory should contain configuration files, DTD files, etc.
        that are specific for the solution.
        
      <SolutionName>/etc/config/inventoryTree/
        This directory is used for Inventory Tree definition files.
        
      <SolutionName>/etc/data/
        This directory is used for load data files.
        
      <SolutionName>/etc/dc_tasks/
        HPE Service Activator's Data Collector utility can be extended with
        custom tasks.  Solution specific data collection tasks can be added to
        this directory.  Custom data collection tasks are *not* deployed to the
        HPE Service Activator runtime system.
      
      <SolutionName>/etc/designer/
        If the solution uses custom workflow nodes and/or custom error/end
        handlers their XML specification can be added to this directory. Note
        that the Java implementation of custom nodes and handler need to be
        added to the 3rd-party directory.  Custom handlers must be added to the
        "handlers" directory whereas the custom handlers must be added to the
        "nodes/<SolutionName>" directory.  Custom nodes should never be added
        to the "nodes/builtin" directory.
        
      <SolutionName>/etc/nls/
        This directory can be used as a place holder for localized version of HP
        Service Activator resource bundles.
      
      <SolutionName>/etc/queues/
	This directory can contain XML files that can be used to create queues
        used in the Queuing Sub-system.

      <SolutionName>/etc/sql/
        This directory can be used for solution specific SQL files - for
        instance if a solution needs custom database tables, sequences, etc.
        Files located in this directory will *not* be deployed into the HP
        Service Activator runtime system.
      
      <SolutionName>/etc/scripts/
        Scripts that are to be executed by the Deployment Manager during a
        deploy or an undeploy operation must be located in this directory.
      
      <SolutionName>/etc/template_files/
        This directory typically contains Java template files (used by the Java
        node or the JavaRule node in the Workflow Manager), XML templates, XSL
        templates, etc.
      
      <SolutionName>/etc/tests/messages/
        This directory can be used for test messages that can be injected into
        the SocketListener module from the HPE Service Activator User Interface.
      
      <SolutionName>/etc/umm/
        This directory can contain XML files that can be used to create roles
        in HPE Service Activator and assign inventory trees, operation types,
        and branch types to roles.
      
      <SolutionName>/etc/web_services/
        This directory may contain XML files that define a web service
        interface to HPE Service Activator as well as WAR files (Web Archives)
        implementing web service interfaces.
      
      <SolutionName>/etc/workflows/
        All workflows in a solution should be located in this directory.
      
      <SolutionName>/etc/xmaps/
        All xmaps in a solution should be located in this directory.
      
      <SolutionName>/install/
        This directory is used internally by the Deployment Manager to keep
        track of the deployment state of a solution.  User's should not change
        anything in this directory.
      
      <SolutionName>/inventory/
        This directory is used for all inventory resource definition files in a
        solution and (if manual inventory deployment is used) for
        customizations to the inventory subsystem.
      
      <SolutionName>/lib/
        This directory can be used for Java classes, Java achieve files, etc.
        that are used by scripts located in the <SolutionName>/bin directory.
        Files located in this directory will *not* be deployed into the HP
        Service Activator runtime system.
      
      <SolutionName>/plugins/
        All plug-ins in a solution should be located in this directory.
      
      <SolutionName>/UI/
        All custom user interface components (HTML, JSPs, JavaScripts, etc.)
        should be located in this directory.
      
      <SolutionName>/var/
        This directory can be used for solution specific log files, temporary
        files etc.  Files located in this directory will *not* be deployed into
        the HPE Service Activator runtime system.
      
  THE PATCH / CUSTOMIZATION DIRECTORY
  =============================================================================
    The directory structure for patches and customizations is identical to that
    of a solution, except that the home directory is different.
    
    Patches must be located in the directory:
      $ACTIVATOR_OPT/solutions/<SolutionName>/patches/<PatchName>
    
    Customizations must be located in the directory:
      $ACTIVATOR_OPT/solutions/<CustomizationName>
